# SweetDependency project configuration file
# You can adjust your custom configuration to your liking here
# You can visit https://github.com/HighCapable/SweetDependency for more help
#
# SweetDependency 项目配置文件
# 你可以在这里调整你喜欢的自定义配置
# 你可以前往 https://github.com/HighCapable/SweetDependency 以获得更多帮助

# Configure preferences
# 配置偏好设置
preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

# Configure repositories used by dependencies
# 配置依赖使用的存储库
repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

# Configure plugins that need to be used
# For example:
# plugins:
#   org.jetbrains.kotlin.jvm:
#     version: +
#
# 配置需要使用的插件依赖
# 例如:
# plugins:
#   org.jetbrains.kotlin.jvm:
#     version: +
plugins:
  com.android.application:
    version: 8.1.2
  org.jetbrains.kotlin.android:
    version: 1.9.10
  com.google.dagger.hilt.android:
    version: 2.48.1
  com.google.devtools.ksp:
    version: 1.9.10-1.0.13
libraries:
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      version: 3.5.1
  androidx.compose:
    compose-bom:
      version: 2023.10.01
  androidx.compose.ui:
    ui-test-junit4:
      version: <no-spec>
    ui-tooling:
      version: <no-spec>
    ui-test-manifest:
      version: 1.6.0-alpha08
    ui:
      version: <no-spec>
    ui-graphics:
      version: <no-spec>
    ui-tooling-preview:
      version: <no-spec>
  androidx.compose.material:
    material-icons-extended:
      version: 1.5.4
  androidx.hilt:
    hilt-navigation-compose:
      version: 1.0.0
  com.google.dagger:
    hilt-android:
      version: 2.48.1
    hilt-android-compiler:
      version: 2.48.1
  androidx.navigation:
    navigation-compose:
      version: 2.7.4
  com.blankj:
    utilcodex:
      version: 1.31.1
  io.coil-kt:
    coil-compose:
      version: 2.4.0
  io.ktor:
    ktor-network:
      version: 2.3.5
    ktor-client-core:
      version: 2.3.5
    ktor-client-android:
      version: 2.3.5
  androidx.core:
    core-ktx:
      version: 1.12.0
  androidx.lifecycle:
    lifecycle-runtime-ktx:
      version: 2.6.2
  androidx.activity:
    activity-compose:
      version: 1.8.0
  androidx.compose.material3:
    material3:
      version: 1.2.0-alpha10
  junit:
    junit:
      version: 4.13.2